### PR TITLE
System tray integration

### PR DESCRIPTION
**Pull request by USA-RedDragon**
Closes: #83 

This adds functionality to allow this tool to run minimized to the system tray. I have not changed any default behaviors and have not enabled any of the new options by default.

This can be extended in the future with a few ideas:
- An option to automatically install as a Windows Service (this would be useful for avoiding UAC prompts every boot)
- Extending the Tray menu to include options like toggling injection, restarting Nginx/Image server, etc.

I have allowed edits by maintainers on the PR. A code review would be nice as well.

### CODE REVIEW

**Comment by USA-RedDragon** [comment]
Figured a few screenshots wouldn't hurt.

image
image
image

**Comment by USA-RedDragon** [comment]
Not ready to merge yet. Been using this version for a few days now. Seemingly the icon gets rotated out and I can end up with multiple system tray icons for this.

**Comment by derekhe** [comment]
Sure, please make sure it is stable and I will test & merge it :)
Thanks for your effort.

**Comment by USA-RedDragon** [comment]
I haven't been seeing the duplicated icons in the last couple of days with those commits above. Seems related to https://github.com/electron/electron/issues/8597

**Comment by derekhe** [comment]
I will test and will merge it when it is stable.

**Pull request closed without merging**
