### PR TITLE
Adaptation for mapbox api

### PR DESCRIPTION
**Pull request by h0wardch3ng**
This PR includes a default mapbox token that can be loaded with 200,000 tiles for free.
However, I would suggest providing a feature in the software interface for the user to fill in the token and save it themselves.

Snipaste_2022-01-10_17-01-38

(This PR does not include the function for the user to fill in the token and save it in the program GUI, here's my suggestion)

### CODE REVIEW

**Comment by derekhe** [comment]
I think the mapbox token is still neeeded for individuals and you can implement that if you can. I can do a merge after than.
If you are not familiar with Vue I can do it for you.

**Comment by h0wardch3ng** [comment]
Okay, thanks for the software you created!

**Comment by derekhe** [comment]
How do you think the quality mapbox provide? I checked some areas in China it is not so good.
image

**Comment by h0wardch3ng** [comment]
I think this tool is not just for China, but for the world.
Happy Chinese New Year.

**Comment by derekhe** [comment]
I added the mapbox support in 3.2.1, please upgrade and enjoy 💯

**Pull request closed without merging**
